name: image_grid_view
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.1
  flutter_hooks: ^0.18.5+1
  styled_widget: ^0.4.1
  photo_view: ^0.14.0
